CREATE TABLE directors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text,
  birthdate date
);

CREATE TABLE movies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  director_id bigint NOT NULL REFERENCES directors(id),
  title text,
  year bigint,
  running_time bigint,
  budget decimal,
  box_office decimal
);

INSERT INTO directors (name, birthdate)
VALUES
  ('George Lucas', 'May 14, 1944'),
  ('Irvin Kershner', 'Apr 29, 1923'),
  ('Richard Marquand', 'Sept 22, 1937'),
  ('J.J. Abrams', 'Jun 27 1966'),
  ('Rian Johnson', 'Dec 17, 1973'),
  ('Dave Filoni', 'Jun 7, 1974'),
  ('Gareth Edwards', 'Jul 13, 1975'),
  ('Ron Howard', 'Mar 1, 1954'),
  ('Patty Jenkins', 'Jul 24, 1971')
;

INSERT INTO movies (director_id, title, year, running_time, budget, box_office )
VALUES 
 (1, 'Episode IV - A New Hope', 1977, 121, 11, 776)
,(2, 'Episode V - The Empire Strikes Back', 1980, 124, 30.5, 549)
,(3, 'Episode VI - Return of the Jedi', 1983, 132, 42.7, 475.1)
,(1, 'Episode I - Phantom Menace', 1999, 133, 115, 1027)
,(1, 'Episode II - Attack of the Clones', 2002, 142, 115, 653.8)
,(1, 'Episode III - Revenge of the Sith', 2005, 140, 113, 868.4)
,(4, 'Star Wars: The Force Awakens', 2015, 138, 306, 2069)
,(5, 'Star Wars: The Last Jedi', 2017, 152, 317, 1333)
,(4, 'Star Wars: The Rise of Skywalker', 2019, 143, 275, 1074)
,(6, 'Star Wars: The Clone Wars', 2008, 98, 8.5, 68.3)
,(7, 'Rogue One: A Star Wars Story', 2016, 134, 220, 1056)
,(8, 'Solo: A Star Wars Story', 2018, 135, 300, 393.2)
,(9, 'Rogue Squadron',NULL ,NULL ,NULL ,NULL)